name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*  # Ou a versão adequada para o seu projeto

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/gerenciadorTarefa

    - name: List directory contents
      run: ls -R

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o ${{github.workspace}}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: grencieTarefas  # Nome do seu aplicativo no Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Configure este segredo no GitHub
